# Generated by Django 5.2.9 on 2026-02-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gmail', models.CharField()),
                ('number', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
